baseURL='https://badgefed.vocalcat.com/'
languageCode = 'en-us'
title = 'BadgeFed Official Blog'
theme = 'PaperMod'

buildFuture = true
buildExpired = true

mainsections = ["post"]

[[menu.main]]
name = "Home"
weight=10
identifier="home"
url = "/"

[params]
title = 'BadgeFed Blog'
author = 'VocalCat'
description = "Empowering decentralized credentialing in the Fediverse through open-source innovation."
fediverseHandle='@badgefed@vocalcat.com'
comments=true