baseURL='https://blogc3mm3g2jhkes6.z22.web.core.windows.net/'
languageCode = 'en-us'
title = 'My New Hugo Site enabled for the Fediverse!'
theme = 'PaperMod'
paginate = 5

buildFuture = true
buildExpired = true

mainsections = ["post"]

[[menu.main]]
name = "Home"
weight=10
identifier="home"
url = "/"

[params]
title = 'BadgeFed Blog'
author = 'VocalCat'
description = "A static site fediverse enabled by activitypub!"
fediverseHandle='@badgefed@vocalcat.com'
comments=true